# -*- coding: utf-8 -*-
"""finalnew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11c-yMKT5JUaLZ1x0BwqmiN3OCfkjBVuB
"""

# SETUP & INSTALL
!pip install -q arxiv pymupdf pdfplumber tqdm pandas numpy spacy sentence-transformers transformers faiss-cpu networkx scikit-learn rank_bm25 rouge-score bert-score matplotlib gradio
!python -m spacy download en_core_web_sm

import os, json, re, time, math, io, requests
from pathlib import Path
from tqdm.auto import tqdm
import numpy as np
import pandas as pd
import spacy
import torch
import networkx as nx
import fitz   # pymupdf
from urllib.parse import quote_plus
from sklearn.metrics.pairwise import cosine_similarity
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
import faiss

from rouge_score import rouge_scorer
from bert_score import score as bert_score
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

nlp = spacy.load("en_core_web_sm")

# === PROJECT PATHS ===
PROJECT = Path("/content/aslrs_project")
RAW = PROJECT / "data" / "raw_pdfs"
TXT = PROJECT / "data" / "text"
PROC = PROJECT / "data" / "processed"
MODELS = PROJECT / "models"

for p in [RAW, TXT, PROC, MODELS]:
    p.mkdir(parents=True, exist_ok=True)

print("Workspace:", PROJECT)
print("GPU available:", torch.cuda.is_available())


def clean_text(s):
    if s is None:
        return ""
    s = s.replace("\r"," ").replace("\n"," ")
    s = re.sub(r"\s+"," ", s).strip()
    return s


def sentence_split_spacy(text, min_chars=30):
    doc = nlp(text)
    sents = [sent.text.strip() for sent in doc.sents if len(sent.text.strip()) >= min_chars]

    if not sents:
        sents = [seg.strip() for seg in re.split(r'(?<=[\.\?\!])\s+', text) if len(seg.strip()) >= min_chars]
    return sents

# arXiv download + PDF → text + corpus building
import arxiv
import time


# Build arXiv query from free text or fielded terms
def build_arxiv_query_from_terms(raw_query):
    """
    Accepts free-form user query or fielded terms like:
    - "ai iot"
    - "cat:cs.CL"
    - "all:\"large language models\""
    Returns a combined arXiv query string.
    """
    terms = []
    for part in re.split(r'[,\n]+', raw_query.strip()):
        p = part.strip()
        if not p:
            continue
        # if user already gave fielded query, keep as is
        if re.match(r'^(cat:|ti:|au:|abs:|all:)', p, re.I):
            terms.append(p)
        else:
            # treat as keyword -> search in "all"
            if " " in p:
                terms.append(f'all:"{p}"')
            else:
                terms.append(f'all:{p}')
    return " OR ".join(terms) if terms else raw_query

# Search arXiv, download PDFs, and save basic metadata
def download_papers_and_save_metadata(query_string, max_results=30, prefer_arxiv_abstract=True):
    """
    1) Search arXiv using query_string.
    2) Download PDFs into RAW/.
    3) Save metadata (paper_id, title, abstract, authors) into PROC/metadata.json.

    Returns:
        papers (list[arxiv.Result])
        meta_list (list[dict])
    """
    q = build_arxiv_query_from_terms(query_string)
    print("Constructed arXiv query:", q)

    time.sleep(2)

    search = arxiv.Search(
        query=q,
        max_results=max_results,
        sort_by=arxiv.SortCriterion.SubmittedDate
    )
    papers = list(search.results())
    print("Found", len(papers), "results. Downloading PDFs (skipping cached)...")

    meta_list = []
    for p in tqdm(papers):

        time.sleep(1.2)

        arxiv_id = p.get_short_id()   # e.g., 2105.12345
        pdf_path = RAW / f"{arxiv_id}.pdf"
        if not pdf_path.exists():
            try:
                p.download_pdf(filename=str(pdf_path))
            except Exception as e:
                print("Download failed for", arxiv_id, "error:", e)
                continue

        title = p.title.strip() if getattr(p, "title", None) else ""
        summary = p.summary.strip() if getattr(p, "summary", None) else ""
        authors = [a.name for a in p.authors] if getattr(p, "authors", None) else []
        meta_list.append({
            "paper_id": arxiv_id,
            "title": title,
            "abstract": summary if prefer_arxiv_abstract else "",
            "authors": authors
        })

    # Save raw metadata
    json.dump(meta_list, open(PROC/"metadata.json", "w"), indent=2)
    print("Saved metadata for", len(meta_list), "papers to", PROC/"metadata.json")
    return papers, meta_list


def pdf_to_text(pdf_path: Path) -> str:
    """
    Reads full PDF and concatenates page text.
    """
    try:
        doc = fitz.open(str(pdf_path))
        pages = []
        for page in doc:
            pages.append(page.get_text("text"))
        return "\n".join(pages)
    except Exception as e:
        print("PDF parse error:", pdf_path, "error:", e)
        return ""

#  Build processed metadata
def extract_texts_and_build_meta(use_arxiv_meta=True):
    """
    For each PDF in RAW/:
      - Extract raw text -> save in TXT/{paper_id}.txt
      - Build improved metadata with:
            paper_id, title, abstract

    If arXiv metadata exists, we prefer:
      - arXiv title
      - arXiv abstract (if use_arxiv_meta=True)
    Otherwise we heuristically extract an abstract-like section
    from the PDF text.

    Saves:
      - PROC/metadata_processed.json

    Returns:
      meta_list (list[dict])
    """
    # Load arXiv metadata if present
    meta_by_arxiv = {}
    if (PROC/"metadata.json").exists():
        try:
            raw_meta = json.load(open(PROC/"metadata.json"))
            meta_by_arxiv = {m["paper_id"]: m for m in raw_meta}
        except Exception as e:
            print("Warning: could not read metadata.json:", e)

    meta_list = []
    pdf_files = sorted(RAW.glob("*.pdf"))
    print("Extracting text from", len(pdf_files), "PDFs...")

    for pdf in tqdm(pdf_files):
        pid = pdf.stem
        txt_path = TXT / f"{pid}.txt"

        # Extract and cache text if not present
        if not txt_path.exists():
            rawtxt = pdf_to_text(pdf)
            txt_path.write_text(rawtxt, encoding="utf-8")
        else:
            rawtxt = txt_path.read_text(encoding="utf-8")

        rawtxt_clean = clean_text(rawtxt)

        # Prefer arXiv title/abstract where available
        title = ""
        abstract = ""

        if pid in meta_by_arxiv:
            title = meta_by_arxiv[pid].get("title", "") or ""
            if use_arxiv_meta:
                abstract = meta_by_arxiv[pid].get("abstract", "") or ""

        # If no abstract from arXiv, try to extract from PDF text
        if not abstract:
            # Look for 'Abstract' section heuristically
            m = re.search(
                r'(?i)abstract[:\s]\s*(.+?)(?=\n(?:1\s+introduction|introduction|1\.\s+|keywords|1\s+))',
                rawtxt,
                re.S
            )
            if m:
                abstract = clean_text(m.group(1))

        # Final fallback: first ~800 chars of the text
        if not abstract:
            abstract = rawtxt_clean[:800]

        meta_list.append({
            "paper_id": pid,
            "title": title,
            "abstract": abstract
        })

    json.dump(meta_list, open(PROC/"metadata_processed.json", "w"), indent=2)
    print("Extraction complete. Papers processed:", len(meta_list))
    return meta_list

# Build corpus: doc texts, sentence lists, doc ids
def build_corpus_from_txt(min_sent_len=30, min_sents_per_doc=5):
    """
    Uses TXT/*.txt and PROC/metadata_processed.json to build:
        docs: list[str]          (full doc text as one string)
        doc_sentences: list[list[str]]  (each doc as list of sentences)
        doc_ids: list[str]       (paper ids)

    Abstract sentences are prepended (de-duplicated) for better summarization.
    """
    if (PROC/"metadata_processed.json").exists():
        meta_list = json.load(open(PROC/"metadata_processed.json"))
    else:
        meta_list = []
    meta_by_id = {d["paper_id"]: d for d in meta_list}

    docs = []
    doc_sentences = []
    doc_ids = []

    txt_files = sorted(TXT.glob("*.txt"))
    print("Building corpus from", len(txt_files), "TXT files...")

    for txt_file in tqdm(txt_files):
        pid = txt_file.stem
        raw = clean_text(txt_file.read_text(encoding="utf-8"))
        sents = sentence_split_spacy(raw, min_chars=min_sent_len)

        # Prepend abstract sentences if available
        if pid in meta_by_id and meta_by_id[pid].get("abstract"):
            abs_sents = sentence_split_spacy(meta_by_id[pid]["abstract"], min_chars=20)
            combined = []
            for s in abs_sents + sents:
                if s not in combined:
                    combined.append(s)
            sents = combined

        if len(sents) < min_sents_per_doc:
            continue

        docs.append(" ".join(sents))
        doc_sentences.append(sents)
        doc_ids.append(pid)

    print("Loaded docs:", len(docs))
    pd.DataFrame({"paper_id": doc_ids}).to_csv(PROC/"doc_ids.csv", index=False)
    return docs, doc_sentences, doc_ids

# Retrieval indices (BM25 + dense embeddings + FAISS)

def build_indices(docs, embed_model_name="all-mpnet-base-v2", batch_size=16):
    """
    Builds:
      - BM25 index over tokenized docs
      - Dense embeddings using SentenceTransformer
      - FAISS index over normalized embeddings (cosine similarity via inner product)
    """
    print("Building BM25 index...")
    tokenized_for_bm25 = [doc.split() for doc in docs]
    bm25 = BM25Okapi(tokenized_for_bm25)
    print("BM25 index built.")

    print(f"Loading SentenceTransformer embedding model: {embed_model_name}")
    embed_model = SentenceTransformer(embed_model_name)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    embed_model = embed_model.to(device)
    print("Encoding documents...")
    doc_embs = embed_model.encode(
        docs,
        convert_to_numpy=True,
        show_progress_bar=True,
        batch_size=batch_size
    )

    # FAISS index for cosine similarity (normalize first, then use inner product)
    faiss.normalize_L2(doc_embs)
    d = doc_embs.shape[1]
    index = faiss.IndexFlatIP(d)
    index.add(doc_embs)
    print("FAISS index built. Vectors:", index.ntotal)
    return bm25, embed_model, doc_embs, index

# --- Retrieval helpers (BM25 + dense) ---

def retrieve_bm25_local(bm25, doc_ids, query, top_k=5):
    tokenized_q = query.split()
    scores = bm25.get_scores(tokenized_q)
    idxs = np.argsort(scores)[::-1][:top_k]
    return [(doc_ids[i], float(scores[i])) for i in idxs]

def retrieve_dense_local(embed_model, index, doc_ids, query, top_k=5):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    q_emb = embed_model.encode([query], convert_to_numpy=True, device=device)
    faiss.normalize_L2(q_emb)
    D, I = index.search(q_emb, top_k)
    results = []
    for j, i in enumerate(I[0]):
        results.append((doc_ids[int(i)], float(D[0][j])))
    return results

# Extractive (BERTSUM-style) + Abstractive (PEGASUS) summarization

# Install bert-extractive-summarizer if not already installed
!pip install -q bert-extractive-summarizer

from summarizer import Summarizer
from transformers import PegasusForConditionalGeneration, PegasusTokenizer



print("Loading BERT-based extractive summarizer (BERTSUM-style)...")
bertsum_model = Summarizer()  # uses bert-base-uncased by default under the hood

def extractive_bertsum_summary(sentences, top_k=3):
    """
    Use BERT-based extractive summarizer.
    We join sentences into one text, let BERT pick important sentences,
    then map back to the original sentence list and return top_k in order.
    """
    if len(sentences) == 0:
        return []

    full_text = " ".join(sentences)

    summary_text = bertsum_model(full_text)

    # Split summary back to sentences and align by exact match / substring
    summary_sents = sentence_split_spacy(summary_text, min_chars=10)
    selected = []
    used_indices = set()

    for ss in summary_sents:
        for i, s in enumerate(sentences):
            if i in used_indices:
                continue
            # simple containment heuristic
            if ss.strip() in s or s in ss.strip():
                selected.append((i, s, 1.0))  # score is dummy here
                used_indices.add(i)
                break


    if len(selected) < top_k:
        for i, s in enumerate(sentences):
            if len(selected) >= top_k:
                break
            if i not in used_indices:
                selected.append((i, s, 0.5))

    # Sort by original order
    selected = sorted(selected, key=lambda x: x[0])
    return selected[:top_k]


# PEGASUS Abstractive Summarizer

print("Loading PEGASUS abstractive model (google/pegasus-cnn_dailymail)...")
pegasus_model_name = "google/pegasus-cnn_dailymail"
pegasus_tokenizer = PegasusTokenizer.from_pretrained(pegasus_model_name)
pegasus_model = PegasusForConditionalGeneration.from_pretrained(
    pegasus_model_name,
    device_map="auto",
    low_cpu_mem_usage=True
)
device = pegasus_model.device

def abstractive_summarize_long_text(text, max_len=160, min_len=40, chunk_size=1024):
    """
    PEGASUS-based abstractive summarization for long docs:
      1) Split text into chunks of up to chunk_size characters
      2) Summarize each chunk
      3) Concatenate partial summaries
      4) Run a final PEGASUS pass over combined summary
    """
    text = clean_text(text)
    if not text:
        return ""

    # Rough character-based chunking
    chunks = [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]
    partial_summaries = []

    for chunk in chunks:
        inputs = pegasus_tokenizer(
            chunk,
            truncation=True,
            padding="longest",
            max_length=1024,
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            summary_ids = pegasus_model.generate(
                **inputs,
                max_length=max_len,
                min_length=min_len,
                length_penalty=1.0,
                num_beams=4,
                early_stopping=True
            )

        summary_text = pegasus_tokenizer.decode(summary_ids[0], skip_special_tokens=True)
        partial_summaries.append(summary_text)

    combined = " ".join(partial_summaries)

    # Final fusion pass
    fusion_inputs = pegasus_tokenizer(
        combined,
        truncation=True,
        padding="longest",
        max_length=1024,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        fusion_ids = pegasus_model.generate(
            **fusion_inputs,
            max_length=max_len,
            min_length=min_len,
            length_penalty=1.0,
            num_beams=4,
            early_stopping=True
        )

    final_summary = pegasus_tokenizer.decode(fusion_ids[0], skip_special_tokens=True)
    return final_summary

# Evaluation (ROUGE + BERTScore) + Pipeline orchestration
# CITATION GRAPH BUILDER (Integrated into Pipeline)

import requests
import networkx as nx
import time
from urllib.parse import quote_plus

SEM_SCHOLAR_URL = "https://api.semanticscholar.org/graph/v1/paper/"
HEADERS = {"User-Agent": "Scientific-LitReview-Project/1.0"}
SLEEP = 0.5  # polite API delay

def fetch_references(pid):
    """Fetch references from Semantic Scholar for a given arXiv ID."""
    paper_id = f"ARXIV:{pid}"
    fields = "title,externalIds,references.title,references.externalIds,citations.title,citations.externalIds"
    url = SEM_SCHOLAR_URL + quote_plus(paper_id) + f"?fields={fields}"

    try:
        resp = requests.get(url, headers=HEADERS, timeout=20)
        if resp.status_code != 200:
            return []
        data = resp.json()
        refs = data.get("references", [])
        time.sleep(SLEEP)
        return refs
    except:
        return []

def extract_arxiv_id(ext):
    """Extract arXiv ID from Semantic Scholar externalIds."""
    if not isinstance(ext, dict):
        return None
    for key in ["ArXiv", "arXiv", "ARXIV"]:
        if key in ext:
            return ext[key].replace("arXiv:", "").strip()
    return None

from sklearn.metrics.pairwise import cosine_similarity

def build_similarity_edges(doc_embs, doc_ids, top_k=3):
    """
    Builds edges based on semantic similarity.
    For each paper, connect it to its top_k most similar papers.
    """
    edges = []
    sims = cosine_similarity(doc_embs)

    for i in range(len(doc_ids)):
        # top-k most similar (skip itself)
        idxs = sims[i].argsort()[::-1][1:top_k+1]
        for j in idxs:
            edges.append((doc_ids[i], doc_ids[j]))

    return edges

def build_citation_graph(doc_ids):
    """
    Build citation graph using ONLY semantic similarity (Option C).
    """

    print("Building similarity-based citation graph...")

    # Load doc embeddings
    doc_embs = np.load(PROC/"doc_embs.npy")

    # Create directed graph
    G = nx.DiGraph()

    # Add nodes
    for pid in doc_ids:
        G.add_node(pid)

    # Build similarity edges
    sim_edges = build_similarity_edges(doc_embs, doc_ids, top_k=3)

    # Add edges
    for a, b in sim_edges:
        G.add_edge(a, b)

    print("Graph Complete → Nodes:", G.number_of_nodes(),
          "Edges:", G.number_of_edges())

    # compute centrality
    pagerank_scores = nx.pagerank(G)
    indegree = dict(G.in_degree())
    outdegree = dict(G.out_degree())

    return G, pagerank_scores, indegree, outdegree




# Evaluation setup
scorer = rouge_scorer.RougeScorer(['rouge1','rouge2','rougeL'], use_stemmer=True)

def evaluate_summary(reference, candidate):
    """
    Compute ROUGE-1/2/L and BERTScore-F1 between reference and candidate.
    Returns empty dict if reference too short.
    """
    reference = clean_text(reference)
    candidate = clean_text(candidate)

    if not reference or len(reference.split()) < 10:
        return {}

    rouge_scores = scorer.score(reference, candidate)
    # BERTScore can be slow, but more meaningful
    P, R, F1 = bert_score(
        [candidate],
        [reference],
        lang='en',
        rescale_with_baseline=True
    )

    return {
        "rouge1": float(rouge_scores['rouge1'].fmeasure),
        "rouge2": float(rouge_scores['rouge2'].fmeasure),
        "rougeL": float(rouge_scores['rougeL'].fmeasure),
        "bertscore_f1": float(F1[0])
    }

  # Information Retrieval Evaluation Metrics: Precision, Recall, F1

def compute_ir_metrics(query, retrieved_pids, meta_by_id):
    """
    Computes Precision, Recall, and F1-score for Information Retrieval.
    Ground truth relevance = title/abstract contains ANY query word.
    """

    q_words = query.lower().split()

    # ---- Step 1: Build Ground Truth Relevant Papers ----
    gt_relevant = []
    for pid, meta in meta_by_id.items():
        text = (meta.get("title", "") + " " + meta.get("abstract", "")).lower()
        if any(w in text for w in q_words):
            gt_relevant.append(pid)

    total_relevant = len(gt_relevant)
    if total_relevant == 0:
        return {
            "precision": 0,
            "recall": 0,
            "f1": 0,
            "relevant_found": 0,
            "total_relevant": 0
        }

    # Count Relevant Retrieved
    relevant_found = sum(1 for pid in retrieved_pids if pid in gt_relevant)

    precision = relevant_found / len(retrieved_pids)
    recall = relevant_found / total_relevant
    f1 = 2 * precision * recall / (precision + recall + 1e-9)

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "relevant_found": relevant_found,
        "total_relevant": total_relevant
    }



# Full pipeline for a search query

def run_pipeline_for_query(query, max_results=20, embed_model_name="all-mpnet-base-v2"):
    """
    End-to-end:
      1) arXiv download (max_results)
      2) PDF -> text + metadata
      3) Build corpus
      4) Build indices (BM25 + dense + FAISS)

    Returns a 'state' dict reused for searches.
    """
    # 1) download from arXiv
    papers, raw_meta = download_papers_and_save_metadata(query, max_results=max_results, prefer_arxiv_abstract=True)

    # 2) extract texts + build processed metadata
    meta_list = extract_texts_and_build_meta(use_arxiv_meta=True)

    # 3) build corpus
    docs, doc_sentences, doc_ids = build_corpus_from_txt()
    if len(docs) == 0:
        raise RuntimeError("No documents found after preprocessing. Try increasing max_results or check PDF extraction.")

    # 4) build indices
    bm25, embed_model, doc_embs, index = build_indices(docs, embed_model_name=embed_model_name)

    # Persist basic doc index
    np.save(PROC/"doc_embs.npy", doc_embs)
    json.dump({"doc_ids": doc_ids}, open(PROC/"doc_index.json","w"))
    print("Pipeline finished: docs:", len(docs))

    # STEP 5: Build Citation Graph
    meta_by_id = {m['paper_id']: m for m in meta_list}
    G, pagerank_scores, indegree, outdegree = build_citation_graph(doc_ids)

    print("Pipeline finished: docs:", len(docs))

    return {
        "papers": papers,
        "meta_list": meta_list,
        "docs": docs,
        "doc_sentences": doc_sentences,
        "doc_ids": doc_ids,
        "bm25": bm25,
        "embed_model": embed_model,
        "doc_embs": doc_embs,
        "index": index,

        # Citation Graph Components
        "citation_graph": G,
        "pagerank": pagerank_scores,
        "indegree": indegree,
        "outdegree": outdegree,
    }



def pipeline_query_demo_from_state(state, query, method='dense', top_k=5):
    """
    Using a pre-built 'state', run retrieval + summarization + evaluation.

    For each retrieved paper, we compute:
      - extractive summary (BERTSUM-style)
      - abstractive summary (PEGASUS)
      - evaluation vs paper abstract for BOTH summaries
    """
    docs = state['docs']
    doc_sentences = state['doc_sentences']
    doc_ids = state['doc_ids']
    bm25 = state['bm25']
    embed_model = state['embed_model']
    index = state['index']
    meta_by_id = {m['paper_id']: m for m in state['meta_list']}

    # Retrieval
    if method == 'dense':
        retrieved = retrieve_dense_local(embed_model, index, doc_ids, query, top_k=top_k)
    else:
        retrieved = retrieve_bm25_local(bm25, doc_ids, query, top_k=top_k)

    #  Compute IR metrics
    retrieved_pids = [pid for pid, score in retrieved]
    ir_scores = compute_ir_metrics(query, retrieved_pids, meta_by_id)

    results = []

    for pid, score in retrieved:
        idx = doc_ids.index(pid)
        doc_text = docs[idx]
        sentences = doc_sentences[idx]
        meta = meta_by_id.get(pid, {})
        ref_abs = meta.get('abstract', "")

        # Extractive (BERTSUM)
        extractive_info = extractive_bertsum_summary(sentences, top_k=3)
        extractive_summary = " ".join([t[1] for t in extractive_info])

        # Abstractive (PEGASUS)
        abstractive_summary = abstractive_summarize_long_text(doc_text[:20000])

        # Evaluations (vs reference abstract)
        eval_extractive = evaluate_summary(ref_abs, extractive_summary) if ref_abs else {}
        eval_abstractive = evaluate_summary(ref_abs, abstractive_summary) if ref_abs else {}

        results.append({
            "paper_id": pid,
            "score": score,
            "title": meta.get('title', ""),
            "reference_abstract": ref_abs,
            "extractive_info": extractive_info,
            "extractive_summary": extractive_summary,
            "abstractive_summary": abstractive_summary,
            "eval_extractive": eval_extractive,
            "eval_abstractive": eval_abstractive
        })

    return {
        "ir_scores": ir_scores,
        "results": results
    }

# Visualization helpers + Gradio UI
import matplotlib.pyplot as plt
import networkx as nx

# --------------------------------------
# YEAR DISTRIBUTION GRAPH HELPERS
# --------------------------------------

def get_year_from_arxiv_id(pid):
    try:
        # arXiv IDs start with YYMM.xxxxx (post 2000)
        yy = int(pid[:2])
        return 2000 + yy
    except:
        return None


def plot_year_distribution(doc_ids):
    years = []
    for pid in doc_ids:
        y = get_year_from_arxiv_id(pid)
        if y:
            years.append(y)

    if not years:
        fig, ax = plt.subplots()
        ax.text(0.5, 0.5, "No year data available", ha="center")
        ax.axis("off")
        return fig

    year_counts = pd.Series(years).value_counts().sort_index()

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(year_counts.index.astype(str), year_counts.values,
           color="skyblue", edgecolor="black")

    ax.set_title("Year Distribution", fontsize=16, fontweight="bold")
    ax.set_xlabel("Year")
    ax.set_ylabel("Number of Papers")
    ax.tick_params(axis='x', rotation=45)

    plt.tight_layout()
    return fig

def visualize_citation_graph(G, pagerank_scores=None, max_nodes=40):
    if G.number_of_nodes() == 0:
        fig, ax = plt.subplots(figsize=(6, 4))
        ax.text(0.5, 0.5, "No citation graph available", ha="center")
        ax.axis("off")
        return fig

    # Select nodes
    if pagerank_scores:
        top_nodes = sorted(pagerank_scores.items(), key=lambda x: x[1], reverse=True)[:max_nodes]
        nodes_to_show = [n for n, _ in top_nodes]
    else:
        indeg = dict(G.in_degree())
        top_nodes = sorted(indeg.items(), key=lambda x: x[1], reverse=True)[:max_nodes]
        nodes_to_show = [n for n, _ in top_nodes]

    H = G.subgraph(nodes_to_show)

    # Node coloring
    if pagerank_scores:
        colors = [pagerank_scores[n] for n in H.nodes()]
    else:
        colors = "lightblue"

    fig = plt.figure(figsize=(10, 8))
    pos = nx.spring_layout(H, seed=42, k=0.4)

    nx.draw_networkx_nodes(
        H, pos, node_color=colors, cmap=plt.cm.plasma, node_size=500
    )
    nx.draw_networkx_edges(
        H, pos, arrowstyle="-|>", arrowsize=12, edge_color="gray"
    )
    nx.draw_networkx_labels(H, pos, font_size=8)

    plt.title("Citation Graph (Top Influential Papers)", fontsize=14)
    plt.axis("off")
    return fig


import gradio as gr

def build_eval_table(results):
    rows = []
    for r in results:
        ex = r.get('eval_extractive', {})
        ab = r.get('eval_abstractive', {})
        rows.append({
            "paper_id": r['paper_id'],
            "title": r['title'][:80],
            "rouge1_ext": ex.get('rouge1', None),
            "rouge2_ext": ex.get('rouge2', None),
            "rougeL_ext": ex.get('rougeL', None),
            "bertF1_ext": ex.get('bertscore_f1', None),
            "rouge1_abs": ab.get('rouge1', None),
            "rouge2_abs": ab.get('rouge2', None),
            "rougeL_abs": ab.get('rougeL', None),
            "bertF1_abs": ab.get('bertscore_f1', None),
        })
    return pd.DataFrame(rows)


_state_cache = {}  # cache state per (query,max_results)


def gradio_search_and_run(query, method, top_k, max_results):
    try:
        key = f"{query}||{int(max_results)}"
        if key not in _state_cache:
            state = run_pipeline_for_query(query, max_results=int(max_results))
            _state_cache[key] = state
        else:
            state = _state_cache[key]

        output = pipeline_query_demo_from_state(
            state, query, method=method, top_k=int(top_k)
        )

        ir_scores = output["ir_scores"]
        results = output["results"]

    except Exception as e:
        return f"Error: {e}", pd.DataFrame(), plt.figure()

    # IR Metrics
    ir_text = (
        "=== INFORMATION RETRIEVAL ACCURACY ===\n"
        f"Precision: {ir_scores['precision']:.3f}\n"
        f"Recall:    {ir_scores['recall']:.3f}\n"
        f"F1-score:  {ir_scores['f1']:.3f}\n"
        f"Relevant papers found: {ir_scores['relevant_found']} / {ir_scores['total_relevant']}\n"
        + "-"*70 + "\n\n"
    )

    display_text = ir_text

    # Summaries + scores
    for r in results:
        display_text += f"Paper: {r['paper_id']} (score={r['score']:.4f})\n"
        display_text += f"Title: {r['title']}\n\n"

        if r['reference_abstract']:
            display_text += "Reference abstract:\n" + r['reference_abstract'][:400] + "\n\n"

        display_text += "=== Extractive Summary ===\n" + r['extractive_summary'] + "\n\n"
        ex = r['eval_extractive']
        if ex:
            display_text += f"ROUGE1={ex.get('rouge1',0):.3f}, ROUGE2={ex.get('rouge2',0):.3f}, ROUGEL={ex.get('rougeL',0):.3f}, BERT={ex.get('bertscore_f1',0):.3f}\n\n"

        display_text += "=== Abstractive Summary ===\n" + r['abstractive_summary'] + "\n\n"
        ab = r['eval_abstractive']
        if ab:
            display_text += f"ROUGE1={ab.get('rouge1',0):.3f}, ROUGE2={ab.get('rouge2',0):.3f}, ROUGEL={ab.get('rougeL',0):.3f}, BERT={ab.get('bertscore_f1',0):.3f}\n\n"

        display_text += "-"*80 + "\n\n"

    df_eval = build_eval_table(results)

    # Build citation graph figure
    G = state["citation_graph"]
    pagerank = state["pagerank"]
    fig1 = visualize_citation_graph(G, pagerank)
    fig2 = plot_year_distribution(state["doc_ids"])
    return display_text, df_eval, fig1, fig2



with gr.Blocks() as demo:
    gr.Markdown("## Automated Scientific Literature Review (with Citation Graph)")

    with gr.Row():
        with gr.Column(scale=2):
            q_input = gr.Textbox(label="Search query", lines=2)
            method = gr.Radio(choices=["dense", "bm25"], value="dense")
            top_k = gr.Slider(1, 10, value=3, step=1)
            max_results = gr.Slider(5, 80, value=20, step=5)
            run_btn = gr.Button("Run pipeline")
        with gr.Column(scale=3):
            output_text = gr.Textbox(label="Summaries + scores", lines=30)

    eval_table = gr.Dataframe(headers=[
        "paper_id","title","rouge1_ext","rouge2_ext","rougeL_ext","bertF1_ext",
        "rouge1_abs","rouge2_abs","rougeL_abs","bertF1_abs"
    ], label="Evaluation Table")

    graph_plot = gr.Plot(label="Citation Graph")
    year_plot = gr.Plot(label="Year Distribution")
    run_btn.click(
    fn=gradio_search_and_run,
    inputs=[q_input, method, top_k, max_results],
    outputs=[output_text, eval_table, graph_plot, year_plot]
)


demo.launch(share=True, debug=True)

